/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brainstorm.PMLIQ.View.panel.list;

import com.brainstorm.PMLIQ.Model.Equipo;
import com.brainstorm.PMLIQ.View.PMLIApp;
import com.brainstorm.PMLIQ.View.actions.CVPDFAction;
import com.brainstorm.PMLIQ.View.actions.EliminarAction;
import com.brainstorm.PMLIQ.View.actions.ModificarEquipoAction;
import com.brainstorm.PMLIQ.View.adapters.EquipoMouseAdapter;
import com.brainstorm.PMLIQ.View.adapters.ItemMouseAdapter;
import com.brainstorm.PMLIQ.View.panel.crearEquipoPanel;
import com.brainstorm.PMLIQ.View.panel.modificarEquipoPanel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Silex RPR
 */
public class EquiposListaPanel extends javax.swing.JPanel implements ListaPanel{

    /**
     * Creates new form EquiposListaPanel
     */
    public EquiposListaPanel() {
        initComponents();
        
        listaTable.setModel(equiposModel);
        listaTable.setColumnSelectionAllowed(false);
        listaTable.setRowSelectionAllowed(true);

        equiposModel.addColumn("Nombre");
        equiposModel.addColumn("Placa de Inventario");
        equiposModel.addColumn("Tipo de Equipo");
        equiposModel.addColumn("Uso de Equipo");
        equiposModel.addColumn("Ubicación");
        
        listaTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        listaTable.addMouseListener(new EquipoMouseAdapter(this, listaTable, equiposModel, "Modificar"));
        
        updateListModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hojasPanel = new javax.swing.JPanel();
        buscarPanel = new javax.swing.JPanel();
        buscarInternalPanel = new javax.swing.JPanel();
        filtroComboBox = new javax.swing.JComboBox();
        buscarTextField = new javax.swing.JTextField();
        separadorLabel = new javax.swing.JLabel();
        accionesPanel = new javax.swing.JPanel();
        nuevoEquipoButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTable = new javax.swing.JTable();

        hojasPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        buscarInternalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR"));

        filtroComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Placa", "Tipo", "Uso", "Ubicacion" }));

        buscarTextField.setForeground(new java.awt.Color(255, 153, 0));
        buscarTextField.setText("Buscar");
        buscarTextField.setDisabledTextColor(new java.awt.Color(255, 204, 0));

        separadorLabel.setText(" :");

        javax.swing.GroupLayout buscarInternalPanelLayout = new javax.swing.GroupLayout(buscarInternalPanel);
        buscarInternalPanel.setLayout(buscarInternalPanelLayout);
        buscarInternalPanelLayout.setHorizontalGroup(
            buscarInternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInternalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        buscarInternalPanelLayout.setVerticalGroup(
            buscarInternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarInternalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buscarInternalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorLabel))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout buscarPanelLayout = new javax.swing.GroupLayout(buscarPanel);
        buscarPanel.setLayout(buscarPanelLayout);
        buscarPanelLayout.setHorizontalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarInternalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buscarPanelLayout.setVerticalGroup(
            buscarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarInternalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        nuevoEquipoButton.setText("Nuevo");
        nuevoEquipoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoEquipoButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accionesPanelLayout = new javax.swing.GroupLayout(accionesPanel);
        accionesPanel.setLayout(accionesPanelLayout);
        accionesPanelLayout.setHorizontalGroup(
            accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoEquipoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        accionesPanelLayout.setVerticalGroup(
            accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(eliminarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuevoEquipoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(listaTable);

        javax.swing.GroupLayout hojasPanelLayout = new javax.swing.GroupLayout(hojasPanel);
        hojasPanel.setLayout(hojasPanelLayout);
        hojasPanelLayout.setHorizontalGroup(
            hojasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hojasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hojasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hojasPanelLayout.createSequentialGroup()
                        .addComponent(buscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accionesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addContainerGap())
        );
        hojasPanelLayout.setVerticalGroup(
            hojasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hojasPanelLayout.createSequentialGroup()
                .addGroup(hojasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hojasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(hojasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoEquipoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoEquipoButtonActionPerformed
        hojasPanel.setVisible(false);
        hojasPanel.removeAll();
        hojasPanel = new crearEquipoPanel();

        PMLIApp.getInstance().getMainWindow().getAppTabPanel().setComponentAt(1, hojasPanel);
    }//GEN-LAST:event_nuevoEquipoButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        EliminarAction eliminar = new EliminarAction("Eliminar", 1, "Equipo", this, 
                                                      listaTable, equiposModel);
        eliminar.actionPerformed(evt);
    }//GEN-LAST:event_eliminarButtonActionPerformed

    public final void updateListModel() {
        
        if (equiposModel.getRowCount() > 0) {
            for (int i = equiposModel.getRowCount() - 1; i > -1; i--) {
                equiposModel.removeRow(i);
            }
        }
        
        List<Equipo> listaEquipos = PMLIApp.getInstance().getSistema().getEquipos();

        for(Equipo e : listaEquipos) {
            equiposModel.addRow(new Object[] {e.getNombre(), e.getPlacaInventario(), e.getTipoEquipo().toString(),
                                              e.getUsoEquipo().toString(), e.getUbicacionEnLaboratorio()});
        }

        listaTable.setModel(equiposModel);
    }
    
    public JPopupMenu createJPopupMenu() {
        JPopupMenu menu = new JPopupMenu();
        JMenuItem modificar = new JMenuItem(new ModificarEquipoAction("Modificar", 1, this,
                                                                listaTable, equiposModel));
        JMenuItem eliminar = new JMenuItem(new EliminarAction("Eliminar", 1, "Equipo", this, 
                                                               listaTable,equiposModel));
        
        JMenuItem hojaVidaPDF = new JMenuItem(new CVPDFAction("Hoja de Vida", listaTable, equiposModel));
 
        JMenuItem planesMantenimientoPDF = new JMenuItem("Planes de Mantenimiento");
        JMenuItem historialesMantenimientoPDF = new JMenuItem("Historiales de Mantenimiento");
        JMenuItem ordenMantenimiento = new JMenuItem("Generar Orden de Mantenimiento");
        
        menu.add(modificar);
        menu.add(eliminar);
        menu.addSeparator();
        menu.add(hojaVidaPDF);
        menu.addSeparator();
        menu.add(planesMantenimientoPDF);
        menu.add(historialesMantenimientoPDF);
        menu.addSeparator();
        menu.add(ordenMantenimiento);
        
        return menu;
    }
    
    private DefaultTableModel equiposModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accionesPanel;
    private javax.swing.JPanel buscarInternalPanel;
    private javax.swing.JPanel buscarPanel;
    private javax.swing.JTextField buscarTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JComboBox filtroComboBox;
    private javax.swing.JPanel hojasPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaTable;
    private javax.swing.JButton nuevoEquipoButton;
    private javax.swing.JLabel separadorLabel;
    // End of variables declaration//GEN-END:variables
}
