/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brainstorm.PMLIQ.View.panel.list;

import com.brainstorm.PMLIQ.Model.Fabricante.Fabricante;
import com.brainstorm.PMLIQ.View.PMLIApp;
import com.brainstorm.PMLIQ.View.actions.EliminarAction;
import com.brainstorm.PMLIQ.View.panel.crearFabricantePanel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Silex RPR
 */
public class fabricantesListaPanel extends javax.swing.JPanel implements ListaPanel {

    /**
     * Creates new form fabricantesListaPanel
     */
    public fabricantesListaPanel() {
        initComponents();
        
        listaTable.setModel(fabricantesModel);
        listaTable.setColumnSelectionAllowed(false);
        listaTable.setRowSelectionAllowed(true);

        fabricantesModel.addColumn("Nombre");
        fabricantesModel.addColumn("Contacto");
        fabricantesModel.addColumn("Telefono");
        fabricantesModel.addColumn("Correo Electronico");

        listaTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        listaTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && !e.isConsumed()) {
                    e.consume();
                    JOptionPane.showMessageDialog(PMLIApp.getInstance().getMainWindow(), "Modificando un fabricante.", 
                                    "Modificando Fabricante", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            @Override
            public void mouseReleased(MouseEvent e) {
                int r = listaTable.rowAtPoint(e.getPoint());
                if (r >= 0 && r < listaTable.getRowCount()) {
                    listaTable.setRowSelectionInterval(r, r);
                } else {
                    listaTable.clearSelection();
                }

                int rowindex = listaTable.getSelectedRow();
                if (rowindex < 0)
                    return;
                if (e.isPopupTrigger() && e.getComponent() instanceof JTable ) {
                    JPopupMenu popup = createJPopupMenu();
                    popup.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
        
        updateListModel();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fabricantesPanel = new javax.swing.JPanel();
        buscarInventarioPanel1 = new javax.swing.JPanel();
        buscarInternalPanel2 = new javax.swing.JPanel();
        filtroComboBox2 = new javax.swing.JComboBox();
        buscarTextField2 = new javax.swing.JTextField();
        separadorLabel2 = new javax.swing.JLabel();
        accionesPanel2 = new javax.swing.JPanel();
        nuevoFabricanteButton = new javax.swing.JButton();
        eliminarFabricanteButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaTable = new javax.swing.JTable();

        buscarInternalPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR"));

        filtroComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nombre", "Contacto", "Correo" }));

        buscarTextField2.setForeground(new java.awt.Color(255, 153, 0));
        buscarTextField2.setText("Buscar");
        buscarTextField2.setDisabledTextColor(new java.awt.Color(255, 204, 0));

        separadorLabel2.setText(" :");

        javax.swing.GroupLayout buscarInternalPanel2Layout = new javax.swing.GroupLayout(buscarInternalPanel2);
        buscarInternalPanel2.setLayout(buscarInternalPanel2Layout);
        buscarInternalPanel2Layout.setHorizontalGroup(
            buscarInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInternalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        buscarInternalPanel2Layout.setVerticalGroup(
            buscarInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarInternalPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buscarInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorLabel2))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout buscarInventarioPanel1Layout = new javax.swing.GroupLayout(buscarInventarioPanel1);
        buscarInventarioPanel1.setLayout(buscarInventarioPanel1Layout);
        buscarInventarioPanel1Layout.setHorizontalGroup(
            buscarInventarioPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInventarioPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buscarInventarioPanel1Layout.setVerticalGroup(
            buscarInventarioPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInventarioPanel1Layout.createSequentialGroup()
                .addComponent(buscarInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        nuevoFabricanteButton.setText("Nuevo");
        nuevoFabricanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoFabricanteButtonActionPerformed(evt);
            }
        });

        eliminarFabricanteButton.setText("Eliminar");
        eliminarFabricanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarFabricanteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accionesPanel2Layout = new javax.swing.GroupLayout(accionesPanel2);
        accionesPanel2.setLayout(accionesPanel2Layout);
        accionesPanel2Layout.setHorizontalGroup(
            accionesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(nuevoFabricanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarFabricanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        accionesPanel2Layout.setVerticalGroup(
            accionesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accionesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoFabricanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarFabricanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaTable.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(listaTable);

        javax.swing.GroupLayout fabricantesPanelLayout = new javax.swing.GroupLayout(fabricantesPanel);
        fabricantesPanel.setLayout(fabricantesPanelLayout);
        fabricantesPanelLayout.setHorizontalGroup(
            fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fabricantesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(fabricantesPanelLayout.createSequentialGroup()
                        .addComponent(buscarInventarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accionesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        fabricantesPanelLayout.setVerticalGroup(
            fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fabricantesPanelLayout.createSequentialGroup()
                .addGroup(fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fabricantesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarInventarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accionesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fabricantesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fabricantesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoFabricanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoFabricanteButtonActionPerformed

        fabricantesPanel.setVisible(false);
        fabricantesPanel.removeAll();
        fabricantesPanel = new crearFabricantePanel(PMLIApp.getInstance().getSistema().getFabricantes());
        
        PMLIApp.getInstance().getMainWindow().getAppTabPanel().setComponentAt(3, fabricantesPanel);
    }//GEN-LAST:event_nuevoFabricanteButtonActionPerformed

    private void eliminarFabricanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarFabricanteButtonActionPerformed
        EliminarAction eliminar = new EliminarAction("Eliminar", 0, "Fabricante", this, 
                                                      listaTable, fabricantesModel);
        eliminar.actionPerformed(evt);
    }//GEN-LAST:event_eliminarFabricanteButtonActionPerformed

    public final void updateListModel() {
        
        if (fabricantesModel.getRowCount() > 0) {
            for (int i = fabricantesModel.getRowCount() - 1; i > -1; i--) {
                fabricantesModel.removeRow(i);
            }
        }
        
        List<Fabricante> listaFabricantes = PMLIApp.getInstance().getSistema().getFabricantes();
        
        for(Fabricante f : listaFabricantes) {
            fabricantesModel.addRow(new Object[] {f.getNombre(),f.getContacto(), f.getTelefonoUno(), f.getCorreo()});
        }
        
        listaTable.setModel(fabricantesModel);
    }
    
    private JPopupMenu createJPopupMenu() {
        JPopupMenu menu = new JPopupMenu();
        JMenuItem modificar = new JMenuItem("Modificar");
        JMenuItem eliminar = new JMenuItem(new EliminarAction("Eliminar", 0, "Fabricante", this, 
                                                                listaTable, fabricantesModel));
        
        menu.add(modificar);
        menu.add(eliminar);
        

        return menu;
    }
    
    private DefaultTableModel fabricantesModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accionesPanel2;
    private javax.swing.JPanel buscarInternalPanel2;
    private javax.swing.JPanel buscarInventarioPanel1;
    private javax.swing.JTextField buscarTextField2;
    private javax.swing.JButton eliminarFabricanteButton;
    private javax.swing.JPanel fabricantesPanel;
    private javax.swing.JComboBox filtroComboBox2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaTable;
    private javax.swing.JButton nuevoFabricanteButton;
    private javax.swing.JLabel separadorLabel2;
    // End of variables declaration//GEN-END:variables
}
