/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brainstorm.PMLIQ.View.panel.list;

import com.brainstorm.PMLIQ.View.PMLIApp;
import com.brainstorm.PMLIQ.View.panel.crearFabricantePanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Silex RPR
 */
public class fabricantesListaPanel extends javax.swing.JPanel {

    /**
     * Creates new form fabricantesListaPanel
     */
    public fabricantesListaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fabricantesPanel = new javax.swing.JPanel();
        buscarInventarioPanel1 = new javax.swing.JPanel();
        buscarInternalPanel2 = new javax.swing.JPanel();
        filtroComboBox2 = new javax.swing.JComboBox();
        buscarTextField2 = new javax.swing.JTextField();
        separadorLabel2 = new javax.swing.JLabel();
        accionesPanel2 = new javax.swing.JPanel();
        nuevoFabricanteButton = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        listaScrollPanel2 = new javax.swing.JScrollPane();
        listaEquiposList2 = new javax.swing.JList();

        buscarInternalPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSCAR"));

        filtroComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buscarTextField2.setForeground(new java.awt.Color(255, 153, 0));
        buscarTextField2.setText("Buscar");
        buscarTextField2.setDisabledTextColor(new java.awt.Color(255, 204, 0));

        separadorLabel2.setText(" :");

        javax.swing.GroupLayout buscarInternalPanel2Layout = new javax.swing.GroupLayout(buscarInternalPanel2);
        buscarInternalPanel2.setLayout(buscarInternalPanel2Layout);
        buscarInternalPanel2Layout.setHorizontalGroup(
            buscarInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInternalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filtroComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        buscarInternalPanel2Layout.setVerticalGroup(
            buscarInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buscarInternalPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(buscarInternalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separadorLabel2))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout buscarInventarioPanel1Layout = new javax.swing.GroupLayout(buscarInventarioPanel1);
        buscarInventarioPanel1.setLayout(buscarInventarioPanel1Layout);
        buscarInventarioPanel1Layout.setHorizontalGroup(
            buscarInventarioPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInventarioPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buscarInventarioPanel1Layout.setVerticalGroup(
            buscarInventarioPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarInventarioPanel1Layout.createSequentialGroup()
                .addComponent(buscarInternalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        nuevoFabricanteButton.setText("Nuevo");
        nuevoFabricanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoFabricanteButtonActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accionesPanel2Layout = new javax.swing.GroupLayout(accionesPanel2);
        accionesPanel2.setLayout(accionesPanel2Layout);
        accionesPanel2Layout.setHorizontalGroup(
            accionesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevoFabricanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        accionesPanel2Layout.setVerticalGroup(
            accionesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accionesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoFabricanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaScrollPanel2.setViewportView(listaEquiposList2);

        javax.swing.GroupLayout fabricantesPanelLayout = new javax.swing.GroupLayout(fabricantesPanel);
        fabricantesPanel.setLayout(fabricantesPanelLayout);
        fabricantesPanelLayout.setHorizontalGroup(
            fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fabricantesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(fabricantesPanelLayout.createSequentialGroup()
                        .addComponent(buscarInventarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(accionesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(listaScrollPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        fabricantesPanelLayout.setVerticalGroup(
            fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fabricantesPanelLayout.createSequentialGroup()
                .addGroup(fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fabricantesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buscarInventarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accionesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaScrollPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fabricantesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fabricantesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoFabricanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoFabricanteButtonActionPerformed

        fabricantesPanel.setVisible(false);
        fabricantesPanel.removeAll();
        fabricantesPanel = new crearFabricantePanel(PMLIApp.getInstance().getSistema().getFabricantes());
        
        PMLIApp.getInstance().getMainWindow().getAppTabPanel().setComponentAt(3, fabricantesPanel);
    }//GEN-LAST:event_nuevoFabricanteButtonActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JPanel accionesPanel2;
    private javax.swing.JPanel buscarInternalPanel2;
    private javax.swing.JPanel buscarInventarioPanel1;
    private javax.swing.JTextField buscarTextField2;
    private javax.swing.JPanel fabricantesPanel;
    private javax.swing.JComboBox filtroComboBox2;
    private javax.swing.JList listaEquiposList2;
    private javax.swing.JScrollPane listaScrollPanel2;
    private javax.swing.JButton nuevoFabricanteButton;
    private javax.swing.JLabel separadorLabel2;
    // End of variables declaration//GEN-END:variables
}
