/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brainstorm.PMLIQ.View.ventana;

import com.brainstorm.PMLIQ.View.panel.list.EquiposListaPanel;
import com.brainstorm.PMLIQ.View.panel.list.ItemsListaPanel;
import com.brainstorm.PMLIQ.View.panel.list.fabricantesListaPanel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import org.pushingpixels.substance.api.SubstanceLookAndFeel;

/**
 *
 * @author Silex RPR
 */
public class MainWindow extends javax.swing.JFrame {
    
    public static int HOMETAB = 0;
    public static int EQUIPOSTAB = 1;
    public static int ITEMSTAB = 2;
    public static int FABRICANTESTAB = 3;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        appTabPanel.setIconAt(HOMETAB, new javax.swing.ImageIcon(getClass().getResource("/iconHome.png")));
        appTabPanel.setIconAt(EQUIPOSTAB, new javax.swing.ImageIcon(getClass().getResource("/iconEquipos2.png")));
        appTabPanel.setIconAt(ITEMSTAB, new javax.swing.ImageIcon(getClass().getResource("/iconInventario.png")));
        appTabPanel.setIconAt(FABRICANTESTAB, new javax.swing.ImageIcon(getClass().getResource("/iconFabricantes.png")));
        
        appTabPanel.setComponentAt(EQUIPOSTAB, new EquiposListaPanel());
        appTabPanel.setComponentAt(ITEMSTAB, new ItemsListaPanel());
        appTabPanel.setComponentAt(FABRICANTESTAB, new fabricantesListaPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appTabPanel = new javax.swing.JTabbedPane();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hojasPanel = new javax.swing.JPanel();
        inventarioPanel = new javax.swing.JPanel();
        fabricantesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        appTabPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO A PMLIQ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPMLIQ.jpg"))); // NOI18N

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(251, 251, 251))))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        appTabPanel.addTab("Inicio", homePanel);

        hojasPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout hojasPanelLayout = new javax.swing.GroupLayout(hojasPanel);
        hojasPanel.setLayout(hojasPanelLayout);
        hojasPanelLayout.setHorizontalGroup(
            hojasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        hojasPanelLayout.setVerticalGroup(
            hojasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        appTabPanel.addTab("Equipos", hojasPanel);

        javax.swing.GroupLayout inventarioPanelLayout = new javax.swing.GroupLayout(inventarioPanel);
        inventarioPanel.setLayout(inventarioPanelLayout);
        inventarioPanelLayout.setHorizontalGroup(
            inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        inventarioPanelLayout.setVerticalGroup(
            inventarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        appTabPanel.addTab("Inventario", inventarioPanel);

        javax.swing.GroupLayout fabricantesPanelLayout = new javax.swing.GroupLayout(fabricantesPanel);
        fabricantesPanel.setLayout(fabricantesPanelLayout);
        fabricantesPanelLayout.setHorizontalGroup(
            fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        fabricantesPanelLayout.setVerticalGroup(
            fabricantesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        appTabPanel.addTab("Fabricantes", fabricantesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appTabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTabbedPane getAppTabPanel() {
        return appTabPanel;
    }

    public void setAppTabPanel(JTabbedPane appTabPanel) {
        this.appTabPanel = appTabPanel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JFrame.setDefaultLookAndFeelDecorated(true);
        SubstanceLookAndFeel.setSkin("org.pushingpixels.substance.api.skin.OfficeSilver2007Skin");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane appTabPanel;
    private javax.swing.JPanel fabricantesPanel;
    private javax.swing.JPanel hojasPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel inventarioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
