/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.brainstorm.PMLIQ.View.listrenderers;

import com.brainstorm.PMLIQ.Model.Fabricante.Fabricante;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;

/**
 *
 * @author Silex RPR
 */
public class ListRendererFabricante extends javax.swing.JPanel {
    /** Creates new form ListRendererEmpleados */
    public ListRendererFabricante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombre = new javax.swing.JLabel();
        labelContacto = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        labelNombre.setText("nombre");
        add(labelNombre);

        labelContacto.setText("contacto");
        add(labelContacto);

        labelTelefono.setText("telefono");
        add(labelTelefono);

        labelCorreo.setText("correo");
        add(labelCorreo);

    }// </editor-fold>//GEN-END:initComponents

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        Fabricante fabricante = (Fabricante)value;

        labelNombre.setText(fabricante.getNombre());
        labelContacto.setText(fabricante.getContacto());
        labelTelefono.setText(fabricante.getTelefonoUno());
        labelCorreo.setText(fabricante.getCorreo());

        if(isSelected){
            this.setBackground(new Color(200, 200, 255));
        }
        else{
            this.setBackground(new Color(255, 255, 255));
        }

        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    * */
}
